### ISSUE TITLE
1.8-1.9

### ISSUE THREAD

**Issue by IanaKhitsko** [Waldemar1488/tpps#6]
8.	Єдиний стиль для всіх сторінок сайту. Однакове розміщення основних блоків сайту (заголовку, рубрик, логотипу)
9.	Наявність навігації на всіх сторінках сайту. Виключення лише для сторінок, що відкриваються у новому вікні і містять інформацію, яка може сприйматися і не в контексті сайту (збільшена картинка, інформація про розробника, стаття, тощо)
===

приведите к общему стилю пунктов 1.1-1.7

**Comment by Waldemar1488** [comment]
Виправлено.
